[supabase]
url = "https://fekjjitgrbcukjqheojg.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZla2pqaXRncmJjdWtqcWhlb2pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwOTAxODQsImV4cCI6MjA4ODY2NjE4NH0.YUxOKXB8VEfnlE3lsJwZIFV8IGadekqgn3ehO14jlm0"